import {
  BarChart3,
  Bot,
  Building2,
  CreditCard,
  FileClock,
  Gauge,
  KeyRound,
  Megaphone,
  MessageCircle,
  Settings2,
  ShieldCheck,
  UsersRound,
} from "lucide-react";
import type { DashboardModule } from "@/types/platform";

export const dashboardModules: DashboardModule[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    description: "Unified workspace overview for tenant health and operations.",
    href: "/dashboard",
    icon: Gauge,
    permissions: ["analytics.read"],
    tiers: ["starter", "business", "enterprise"],
  },
  {
    id: "analytics",
    label: "Analytics",
    description: "Customer, revenue, campaign, sentiment, and AI performance analytics.",
    href: "/analytics",
    icon: BarChart3,
    permissions: ["analytics.read"],
    tiers: ["starter", "business", "enterprise"],
  },
  {
    id: "customers",
    label: "CRM",
    description: "Customer profiles, imports, segmentation, tags, notes, and timelines.",
    href: "/customers",
    icon: UsersRound,
    permissions: ["messages.read"],
    tiers: ["starter", "business", "enterprise"],
    featureFlag: "crm.core",
  },
  {
    id: "conversations",
    label: "Conversations",
    description: "SMS-first inbox with WhatsApp placeholders, AI suggestions, and handoff.",
    href: "/inbox",
    icon: MessageCircle,
    permissions: ["messages.read"],
    tiers: ["starter", "business", "enterprise"],
  },
  {
    id: "ai",
    label: "AI Center",
    description: "Prompts, knowledge base, training, model selection, and quality controls.",
    href: "/ai",
    icon: Bot,
    permissions: ["ai.manage"],
    tiers: ["business", "enterprise"],
    featureFlag: "ai.knowledge_base",
  },
  {
    id: "campaigns",
    label: "Campaigns",
    description: "Campaign builder, scheduling, segmentation, templates, and testing.",
    href: "/dashboard",
    icon: Megaphone,
    permissions: ["messages.write"],
    tiers: ["business", "enterprise"],
    featureFlag: "campaigns.builder",
  },
  {
    id: "billing",
    label: "Billing",
    description: "Subscriptions, invoices, SMS wallet, overages, add-ons, and upgrades.",
    href: "/billing",
    icon: CreditCard,
    permissions: ["billing.manage"],
    tiers: ["starter", "business", "enterprise"],
  },
  {
    id: "developers",
    label: "Developers",
    description: "API keys, webhooks, request analytics, API logs, and docs.",
    href: "/settings",
    icon: KeyRound,
    permissions: ["api.manage", "webhooks.manage"],
    tiers: ["enterprise"],
    roles: ["developer", "organization_owner", "super_admin"],
    featureFlag: "developers.api",
  },
  {
    id: "compliance",
    label: "Compliance",
    description: "Audit logs, suspicious behavior, KYC, review queues, and moderation.",
    href: "/settings",
    icon: FileClock,
    permissions: ["compliance.review"],
    tiers: ["enterprise"],
    featureFlag: "compliance.audit",
  },
  {
    id: "team",
    label: "Team",
    description: "Users, roles, invitations, branches, departments, and assignments.",
    href: "/team",
    icon: Building2,
    permissions: ["users.manage"],
    tiers: ["business", "enterprise"],
  },
  {
    id: "settings",
    label: "Settings",
    description: "Organization, workspace, security, integrations, and tenant defaults.",
    href: "/settings",
    icon: Settings2,
    permissions: ["users.manage", "billing.manage", "api.manage"],
    tiers: ["starter", "business", "enterprise"],
  },
  {
    id: "platform",
    label: "Platform Controls",
    description: "Super-admin organization control, feature flags, abuse, and platform health.",
    href: "/superAdmin",
    icon: ShieldCheck,
    permissions: ["compliance.review", "billing.manage", "ai.manage"],
    tiers: ["enterprise"],
    roles: ["super_admin"],
    featureFlag: "platform.controls",
  },
];

